---
- name: Install OpenSSH OS-specifically via package
  block:
    - name: Import installed OpenSSH version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml
      when: openssh_installed_version is not defined

    - name: Check OpenSSH pkg mgr version
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_os_family }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        openssh_force_install: true
      when:
        - openssh_installed_version is defined
        - openssh_pkg_mgr_version is defined
        - openssh_installed_version != openssh_pkg_mgr_version

    - name: Install OpenSSH package
      when: openssh_installed_version is not defined or openssh_force_install
      block:
        - name: Uninstall current OpenSSH installation
          ansible.builtin.include_tasks: noauto_uninstall.yml
          when: openssh_installed_version is defined and openssh_installed_version != ""

        - name: Install OpenSSH OS-specifically via package
          ansible.builtin.include_tasks: "{{ task_file }}"
          with_first_found:
            - "{{ role_path }}/tasks/noauto_install_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ role_path }}/tasks/noauto_install_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ role_path }}/tasks/noauto_install_{{ ansible_distribution }}.yml"
            - "{{ role_path }}/tasks/noauto_install_{{ ansible_os_family }}.yml"
            - "{{ role_path }}/tasks/noauto_install_{{ ansible_lsb.id }}.yml"
          loop_control:
            loop_var: task_file
